module.exports = [
  { id: "c1", name: "Taylor Swift", image: "/images/celebrities/taylor-swift.jpg" },
  { id: "c2", name: "Cristiano Ronaldo", image: "/images/celebrities/ronaldo.jpg" },
  { id: "c3", name: "Lionel Messi", image: "/images/celebrities/messi.jpg" },
  { id: "c4", name: "Selena Gomez", image: "/images/celebrities/selena-gomez.jpg" },
  { id: "c5", name: "Elon Musk", image: "/images/celebrities/elon-musk.jpg" },
  { id: "c6", name: "Kanye West", image: "/images/celebrities/kanye-west.jpg" },
  { id: "c7", name: "Zendaya", image: "/images/celebrities/zendaya.jpg" },
  { id: "c8", name: "Dwayne Johnson", image: "/images/celebrities/dwayne-johnson.jpg" },
  { id: "c9", name: "Ariana Grande", image: "/images/celebrities/ariana-grande.jpg" },
  { id: "c10", name: "Drake", image: "/images/celebrities/drake.jpg" },
  { id: "c11", name: "Scarlett Johansson", image: "/images/celebrities/scarlett.jpg" },
  { id: "c12", name: "Tom Holland", image: "/images/celebrities/tom-holland.jpg" },
  { id: "c13", name: "Beyoncé", image: "/images/celebrities/beyonce.jpg" },
  { id: "c14", name: "Will Smith", image: "/images/celebrities/will-smith.jpg" },
  { id: "c15", name: "Emma Watson", image: "/images/celebrities/emma-watson.jpg" },
  { id: "c16", name: "Chris Evans", image: "/images/celebrities/chris-evans.jpg" },
  { id: "c17", name: "Rihanna", image: "/images/celebrities/rihanna.jpg" },
  { id: "c18", name: "Johnny Depp", image: "/images/celebrities/johnny-depp.jpg" },
  { id: "c19", name: "Robert Downey Jr.", image: "/images/celebrities/rdj.jpg" },
  { id: "c20", name: "Gal Gadot", image: "/images/celebrities/gal-gadot.jpg" },
];
