module.exports = {
  // SPELLS
  spells: [
    "arrows",
    "barb-barrel",
    "clone",
    "earthquake",
    "fireball",
    "freeze",
    "graveyard",
    "lightning",
    "log",
    "mirror",
    "poison",
    "rage",
    "rocket",
    "royal-delivery",
    "snowball",
    "tornado",
    "void",
    "zap",
    "zap (1)",
    "snowball (1)",
  ],

  // BUILDINGS
  buildings: [
    "barb-hut",
    "bomb-tower",
    "cannon",
    "cannon (1)",
    "furnace",
    "furnace (1)",
    "gob-hut",
    "goblin-cage",
    "goblin-cage (1)",
    "goblin-drill",
    "goblin-drill (1)",
    "inferno",
    "inferno-d",
    "inferno-d (1)",
    "mortar",
    "mortar (1)",
    "pump",
    "tesla",
    "tesla (1)",
    "tombstone",
    "x-bow",
  ],
};
